version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ghana_legal_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ghana_legal
      MONGO_INITDB_ROOT_PASSWORD: ghana_legal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
